// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.7.7
// Generated from `HuyaVirtualActor.jce'
// **********************************************************************

#ifndef __CCVIRTUALACTOR_CCVIRTUALACTOR_KCCVIRTUALACTORPACKETTYPE_H_
#define __CCVIRTUALACTOR_CCVIRTUALACTOR_KCCVIRTUALACTORPACKETTYPE_H_

#include <map>
#include <string>
#include <vector>
#include "jce/Jce.h"



namespace HuyaVirtualActor
{
    enum kHuyaVirtualActorPacketType
    {
        kHuyaVirtualActorPacketType_Points106 = 1,
        kHuyaVirtualActorPacketType_AppleAnchors = 2,
        kHuyaVirtualActorPacketType_SetDriverType = 3,
        kHuyaVirtualActorPacketType_SetBackground = 4,
        kHuyaVirtualActorPacketType_SetModelInfo = 5,
        kHuyaVirtualActorPacketType_SelectActor,
        kHuyaVirtualActorPacketType_EditMaterial,
        kHuyaVirtualActorPacketType_OperateActor,
        kHuyaVirtualActorPacketType_NotifyMaterials,
        kHuyaVirtualActorPacketType_SetThumbnail,
        kHuyaVirtualActorPacketType_UpdateMaterial,
        kHuyaVirtualActorPacketType_UpdateCameraList,
        kHuyaVirtualActorPacketType_SelectCamera,
        kHuyaVirtualActorPacketType_SoundDetectAnchors,
        kHuyaVirtualActorPacketType_ChangeShape,
        kHuyaVirtualActorPacketType_ChangeColor,
        kHuyaVirtualActorPacketType_ChangeEmotion,
        kHuyaVirtualActorPacketType_ChangePosition,
        kHuyaVirtualActorPacketType_Calibration,
        kHuyaVirtualActorPacketType_VirtualInitData,
        kHuyaVirtualActorPacketType_AppleVertices,
        kHuyaVirtualActorPacketType_TafTransDataReq,
        kHuyaVirtualActorPacketType_TafTransDataRsp,
        kHuyaVirtualActorPacketType_TaskDataInfoReq,
        kHuyaVirtualActorPacketType_TaskDataInfoRsp,
        kHuyaVirtualActorPacketType_VirtualInteractiveGameNotice,
        kHuyaVirtualActorPacketType_ConnectHeartBeat,
        kHuyaVirtualActorPacketType_VirtualCurInteractiveGameIdNotice,
        kHuyaVirtualActorPacketType_VirtualRegisterServerNotify,
        kHuyaVirtualActorPacketType_VirtualServerDataNotice,
        kHuyaVirtualActorPacketType_VirtualInitDataToLiveClient,
        kHuyaVirtualActorPacketType_VirtualCameraSwitch,
        kHuyaVirtualActorPacketType_VirtualDataReportEventWithKeyAndValue,
        kHuyaVirtualActorPacketType_VirtualTafDataReport,
        kHuyaVirtualActorPacketType_VirtualMobileInteractiveGameStart,
        kHuyaVirtualActorPacketType_VirtualActorWalk,
        kHuyaVirtualActorPacketType_VirtualGameBkgStream,
        kHuyaVirtualActorPacketType_VirtualActorDataChangeNotify,
        kHuyaVirtualActorPacketType_LiveStatusNotify,
        kHuyaVirtualActorPacketType_GetInteractiveGameInfoList = 101,
        kHuyaVirtualActorPacketType_GetInteractiveGameInfoListRes = 102,
        kHuyaVirtualActorPacketType_StartInteractiveGame = 103,
        kHuyaVirtualActorPacketType_StartInteractiveGameRes = 104,
        kHuyaVirtualActorPacketType_EndInteractiveGame = 105,
        kHuyaVirtualActorPacketType_EndInteractiveGameRes = 106,
        kHuyaVirtualActorPacketType_PKStatusNotify = 107,
        kHuyaVirtualActorPacketType_GiftItemInfoNotify = 108,
        kHuyaVirtualActorPacketType_ChatMessageInfoNotify = 109,
        kHuyaVirtualActorPacketType_InteractiveGameDataNotify = 110,
        kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecovery = 111,
        kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecoveryRes = 112,
        kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatReq = 113,
        kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatRsp = 114,
        kHuyaVirtualActorPacketType_VirtualOwnGameOrnamentNotify = 115,
        kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameReq = 201,
        kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameRes = 202,
        kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameReq = 203,
        kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameRes = 204,
        kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelReq = 205,
        kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelRes = 206,
        kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatReq = 207,
        kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatRsp = 208,
        kHuyaVirtualActorPacketType_VirtualTravelGuessWordsGameNotice = 209,
        kHuyaVirtualActorPacketType_VirtualTravelEmpowermentGameNotice = 210,
        kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameReq = 211,
        kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameRes = 212,
        kHuyaVirtualActorPacketType_Virtual3DPKModeStatusNotify = 301,
        kHuyaVirtualActorPacketType_Virtual3DPKStartStatusNotify = 302,
        kHuyaVirtualActorPacketType_Virtual3DPKGuestActorControl = 303,
        kHuyaVirtualActorPacketType_StartVirtual3DPK = 304,
        kHuyaVirtualActorPacketType_PrepareVirtual3DPK = 305,
        kHuyaVirtualActorPacketType_BattlePresenterInfo = 306,
        kHuyaVirtualActorPacketType_StartNewVirtual3DPK = 307,
        kHuyaVirtualActorPacketType_StartNewVirtual3DPKRsp = 308,
        kHuyaVirtualActorPacketType_Virtual3DPKStatusNotice = 309,
        kHuyaVirtualActorPacketType_EndNewVirtual3DPK = 310,
        kHuyaVirtualActorPacketType_UpdateVirtual3DPKSignal = 311,
        kHuyaVirtualActorPacketType_Enable3DPKNotify = 312,
        kHuyaVirtualActorPacketType_CheckVirtual3DPK = 313,
        kHuyaVirtualActorPacketType_CheckVirtual3DPKRsp = 314,
        kHuyaVirtualActorPacketType_Live2DActorList = 315,
        kHuyaVirtualActorPacketType_DXSharedHandleTransfer = 316,
    };
    inline std::string etos(const kHuyaVirtualActorPacketType & e)
    {
        switch(e)
        {
            case kHuyaVirtualActorPacketType_Points106: return "kHuyaVirtualActorPacketType_Points106";
            case kHuyaVirtualActorPacketType_AppleAnchors: return "kHuyaVirtualActorPacketType_AppleAnchors";
            case kHuyaVirtualActorPacketType_SetDriverType: return "kHuyaVirtualActorPacketType_SetDriverType";
            case kHuyaVirtualActorPacketType_SetBackground: return "kHuyaVirtualActorPacketType_SetBackground";
            case kHuyaVirtualActorPacketType_SetModelInfo: return "kHuyaVirtualActorPacketType_SetModelInfo";
            case kHuyaVirtualActorPacketType_SelectActor: return "kHuyaVirtualActorPacketType_SelectActor";
            case kHuyaVirtualActorPacketType_EditMaterial: return "kHuyaVirtualActorPacketType_EditMaterial";
            case kHuyaVirtualActorPacketType_OperateActor: return "kHuyaVirtualActorPacketType_OperateActor";
            case kHuyaVirtualActorPacketType_NotifyMaterials: return "kHuyaVirtualActorPacketType_NotifyMaterials";
            case kHuyaVirtualActorPacketType_SetThumbnail: return "kHuyaVirtualActorPacketType_SetThumbnail";
            case kHuyaVirtualActorPacketType_UpdateMaterial: return "kHuyaVirtualActorPacketType_UpdateMaterial";
            case kHuyaVirtualActorPacketType_UpdateCameraList: return "kHuyaVirtualActorPacketType_UpdateCameraList";
            case kHuyaVirtualActorPacketType_SelectCamera: return "kHuyaVirtualActorPacketType_SelectCamera";
            case kHuyaVirtualActorPacketType_SoundDetectAnchors: return "kHuyaVirtualActorPacketType_SoundDetectAnchors";
            case kHuyaVirtualActorPacketType_ChangeShape: return "kHuyaVirtualActorPacketType_ChangeShape";
            case kHuyaVirtualActorPacketType_ChangeColor: return "kHuyaVirtualActorPacketType_ChangeColor";
            case kHuyaVirtualActorPacketType_ChangeEmotion: return "kHuyaVirtualActorPacketType_ChangeEmotion";
            case kHuyaVirtualActorPacketType_ChangePosition: return "kHuyaVirtualActorPacketType_ChangePosition";
            case kHuyaVirtualActorPacketType_Calibration: return "kHuyaVirtualActorPacketType_Calibration";
            case kHuyaVirtualActorPacketType_VirtualInitData: return "kHuyaVirtualActorPacketType_VirtualInitData";
            case kHuyaVirtualActorPacketType_AppleVertices: return "kHuyaVirtualActorPacketType_AppleVertices";
            case kHuyaVirtualActorPacketType_TafTransDataReq: return "kHuyaVirtualActorPacketType_TafTransDataReq";
            case kHuyaVirtualActorPacketType_TafTransDataRsp: return "kHuyaVirtualActorPacketType_TafTransDataRsp";
            case kHuyaVirtualActorPacketType_TaskDataInfoReq: return "kHuyaVirtualActorPacketType_TaskDataInfoReq";
            case kHuyaVirtualActorPacketType_TaskDataInfoRsp: return "kHuyaVirtualActorPacketType_TaskDataInfoRsp";
            case kHuyaVirtualActorPacketType_VirtualInteractiveGameNotice: return "kHuyaVirtualActorPacketType_VirtualInteractiveGameNotice";
            case kHuyaVirtualActorPacketType_ConnectHeartBeat: return "kHuyaVirtualActorPacketType_ConnectHeartBeat";
            case kHuyaVirtualActorPacketType_VirtualCurInteractiveGameIdNotice: return "kHuyaVirtualActorPacketType_VirtualCurInteractiveGameIdNotice";
            case kHuyaVirtualActorPacketType_VirtualRegisterServerNotify: return "kHuyaVirtualActorPacketType_VirtualRegisterServerNotify";
            case kHuyaVirtualActorPacketType_VirtualServerDataNotice: return "kHuyaVirtualActorPacketType_VirtualServerDataNotice";
            case kHuyaVirtualActorPacketType_VirtualInitDataToLiveClient: return "kHuyaVirtualActorPacketType_VirtualInitDataToLiveClient";
            case kHuyaVirtualActorPacketType_VirtualCameraSwitch: return "kHuyaVirtualActorPacketType_VirtualCameraSwitch";
            case kHuyaVirtualActorPacketType_VirtualDataReportEventWithKeyAndValue: return "kHuyaVirtualActorPacketType_VirtualDataReportEventWithKeyAndValue";
            case kHuyaVirtualActorPacketType_VirtualTafDataReport: return "kHuyaVirtualActorPacketType_VirtualTafDataReport";
            case kHuyaVirtualActorPacketType_VirtualMobileInteractiveGameStart: return "kHuyaVirtualActorPacketType_VirtualMobileInteractiveGameStart";
            case kHuyaVirtualActorPacketType_VirtualActorWalk: return "kHuyaVirtualActorPacketType_VirtualActorWalk";
            case kHuyaVirtualActorPacketType_VirtualGameBkgStream: return "kHuyaVirtualActorPacketType_VirtualGameBkgStream";
            case kHuyaVirtualActorPacketType_VirtualActorDataChangeNotify: return "kHuyaVirtualActorPacketType_VirtualActorDataChangeNotify";
            case kHuyaVirtualActorPacketType_LiveStatusNotify: return "kHuyaVirtualActorPacketType_LiveStatusNotify";
            case kHuyaVirtualActorPacketType_GetInteractiveGameInfoList: return "kHuyaVirtualActorPacketType_GetInteractiveGameInfoList";
            case kHuyaVirtualActorPacketType_GetInteractiveGameInfoListRes: return "kHuyaVirtualActorPacketType_GetInteractiveGameInfoListRes";
            case kHuyaVirtualActorPacketType_StartInteractiveGame: return "kHuyaVirtualActorPacketType_StartInteractiveGame";
            case kHuyaVirtualActorPacketType_StartInteractiveGameRes: return "kHuyaVirtualActorPacketType_StartInteractiveGameRes";
            case kHuyaVirtualActorPacketType_EndInteractiveGame: return "kHuyaVirtualActorPacketType_EndInteractiveGame";
            case kHuyaVirtualActorPacketType_EndInteractiveGameRes: return "kHuyaVirtualActorPacketType_EndInteractiveGameRes";
            case kHuyaVirtualActorPacketType_PKStatusNotify: return "kHuyaVirtualActorPacketType_PKStatusNotify";
            case kHuyaVirtualActorPacketType_GiftItemInfoNotify: return "kHuyaVirtualActorPacketType_GiftItemInfoNotify";
            case kHuyaVirtualActorPacketType_ChatMessageInfoNotify: return "kHuyaVirtualActorPacketType_ChatMessageInfoNotify";
            case kHuyaVirtualActorPacketType_InteractiveGameDataNotify: return "kHuyaVirtualActorPacketType_InteractiveGameDataNotify";
            case kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecovery: return "kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecovery";
            case kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecoveryRes: return "kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecoveryRes";
            case kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatReq: return "kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatReq";
            case kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatRsp: return "kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatRsp";
            case kHuyaVirtualActorPacketType_VirtualOwnGameOrnamentNotify: return "kHuyaVirtualActorPacketType_VirtualOwnGameOrnamentNotify";
            case kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameReq: return "kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameReq";
            case kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameRes: return "kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameRes";
            case kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameReq: return "kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameReq";
            case kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameRes: return "kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameRes";
            case kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelReq: return "kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelReq";
            case kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelRes: return "kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelRes";
            case kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatReq: return "kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatReq";
            case kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatRsp: return "kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatRsp";
            case kHuyaVirtualActorPacketType_VirtualTravelGuessWordsGameNotice: return "kHuyaVirtualActorPacketType_VirtualTravelGuessWordsGameNotice";
            case kHuyaVirtualActorPacketType_VirtualTravelEmpowermentGameNotice: return "kHuyaVirtualActorPacketType_VirtualTravelEmpowermentGameNotice";
            case kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameReq: return "kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameReq";
            case kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameRes: return "kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameRes";
            case kHuyaVirtualActorPacketType_Virtual3DPKModeStatusNotify: return "kHuyaVirtualActorPacketType_Virtual3DPKModeStatusNotify";
            case kHuyaVirtualActorPacketType_Virtual3DPKStartStatusNotify: return "kHuyaVirtualActorPacketType_Virtual3DPKStartStatusNotify";
            case kHuyaVirtualActorPacketType_Virtual3DPKGuestActorControl: return "kHuyaVirtualActorPacketType_Virtual3DPKGuestActorControl";
            case kHuyaVirtualActorPacketType_StartVirtual3DPK: return "kHuyaVirtualActorPacketType_StartVirtual3DPK";
            case kHuyaVirtualActorPacketType_PrepareVirtual3DPK: return "kHuyaVirtualActorPacketType_PrepareVirtual3DPK";
            case kHuyaVirtualActorPacketType_BattlePresenterInfo: return "kHuyaVirtualActorPacketType_BattlePresenterInfo";
            case kHuyaVirtualActorPacketType_StartNewVirtual3DPK: return "kHuyaVirtualActorPacketType_StartNewVirtual3DPK";
            case kHuyaVirtualActorPacketType_StartNewVirtual3DPKRsp: return "kHuyaVirtualActorPacketType_StartNewVirtual3DPKRsp";
            case kHuyaVirtualActorPacketType_Virtual3DPKStatusNotice: return "kHuyaVirtualActorPacketType_Virtual3DPKStatusNotice";
            case kHuyaVirtualActorPacketType_EndNewVirtual3DPK: return "kHuyaVirtualActorPacketType_EndNewVirtual3DPK";
            case kHuyaVirtualActorPacketType_UpdateVirtual3DPKSignal: return "kHuyaVirtualActorPacketType_UpdateVirtual3DPKSignal";
            case kHuyaVirtualActorPacketType_Enable3DPKNotify: return "kHuyaVirtualActorPacketType_Enable3DPKNotify";
            case kHuyaVirtualActorPacketType_CheckVirtual3DPK: return "kHuyaVirtualActorPacketType_CheckVirtual3DPK";
            case kHuyaVirtualActorPacketType_CheckVirtual3DPKRsp: return "kHuyaVirtualActorPacketType_CheckVirtual3DPKRsp";
            case kHuyaVirtualActorPacketType_Live2DActorList: return "kHuyaVirtualActorPacketType_Live2DActorList";
            case kHuyaVirtualActorPacketType_DXSharedHandleTransfer: return "kHuyaVirtualActorPacketType_DXSharedHandleTransfer";
            default: return "";
        }
    }
    inline int stoe(const std::string & s, kHuyaVirtualActorPacketType & e)
    {
        if(s == "kHuyaVirtualActorPacketType_Points106")  { e=kHuyaVirtualActorPacketType_Points106; return 0;}
        if(s == "kHuyaVirtualActorPacketType_AppleAnchors")  { e=kHuyaVirtualActorPacketType_AppleAnchors; return 0;}
        if(s == "kHuyaVirtualActorPacketType_SetDriverType")  { e=kHuyaVirtualActorPacketType_SetDriverType; return 0;}
        if(s == "kHuyaVirtualActorPacketType_SetBackground")  { e=kHuyaVirtualActorPacketType_SetBackground; return 0;}
        if(s == "kHuyaVirtualActorPacketType_SetModelInfo")  { e=kHuyaVirtualActorPacketType_SetModelInfo; return 0;}
        if(s == "kHuyaVirtualActorPacketType_SelectActor")  { e=kHuyaVirtualActorPacketType_SelectActor; return 0;}
        if(s == "kHuyaVirtualActorPacketType_EditMaterial")  { e=kHuyaVirtualActorPacketType_EditMaterial; return 0;}
        if(s == "kHuyaVirtualActorPacketType_OperateActor")  { e=kHuyaVirtualActorPacketType_OperateActor; return 0;}
        if(s == "kHuyaVirtualActorPacketType_NotifyMaterials")  { e=kHuyaVirtualActorPacketType_NotifyMaterials; return 0;}
        if(s == "kHuyaVirtualActorPacketType_SetThumbnail")  { e=kHuyaVirtualActorPacketType_SetThumbnail; return 0;}
        if(s == "kHuyaVirtualActorPacketType_UpdateMaterial")  { e=kHuyaVirtualActorPacketType_UpdateMaterial; return 0;}
        if(s == "kHuyaVirtualActorPacketType_UpdateCameraList")  { e=kHuyaVirtualActorPacketType_UpdateCameraList; return 0;}
        if(s == "kHuyaVirtualActorPacketType_SelectCamera")  { e=kHuyaVirtualActorPacketType_SelectCamera; return 0;}
        if(s == "kHuyaVirtualActorPacketType_SoundDetectAnchors")  { e=kHuyaVirtualActorPacketType_SoundDetectAnchors; return 0;}
        if(s == "kHuyaVirtualActorPacketType_ChangeShape")  { e=kHuyaVirtualActorPacketType_ChangeShape; return 0;}
        if(s == "kHuyaVirtualActorPacketType_ChangeColor")  { e=kHuyaVirtualActorPacketType_ChangeColor; return 0;}
        if(s == "kHuyaVirtualActorPacketType_ChangeEmotion")  { e=kHuyaVirtualActorPacketType_ChangeEmotion; return 0;}
        if(s == "kHuyaVirtualActorPacketType_ChangePosition")  { e=kHuyaVirtualActorPacketType_ChangePosition; return 0;}
        if(s == "kHuyaVirtualActorPacketType_Calibration")  { e=kHuyaVirtualActorPacketType_Calibration; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualInitData")  { e=kHuyaVirtualActorPacketType_VirtualInitData; return 0;}
        if(s == "kHuyaVirtualActorPacketType_AppleVertices")  { e=kHuyaVirtualActorPacketType_AppleVertices; return 0;}
        if(s == "kHuyaVirtualActorPacketType_TafTransDataReq")  { e=kHuyaVirtualActorPacketType_TafTransDataReq; return 0;}
        if(s == "kHuyaVirtualActorPacketType_TafTransDataRsp")  { e=kHuyaVirtualActorPacketType_TafTransDataRsp; return 0;}
        if(s == "kHuyaVirtualActorPacketType_TaskDataInfoReq")  { e=kHuyaVirtualActorPacketType_TaskDataInfoReq; return 0;}
        if(s == "kHuyaVirtualActorPacketType_TaskDataInfoRsp")  { e=kHuyaVirtualActorPacketType_TaskDataInfoRsp; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualInteractiveGameNotice")  { e=kHuyaVirtualActorPacketType_VirtualInteractiveGameNotice; return 0;}
        if(s == "kHuyaVirtualActorPacketType_ConnectHeartBeat")  { e=kHuyaVirtualActorPacketType_ConnectHeartBeat; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualCurInteractiveGameIdNotice")  { e=kHuyaVirtualActorPacketType_VirtualCurInteractiveGameIdNotice; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualRegisterServerNotify")  { e=kHuyaVirtualActorPacketType_VirtualRegisterServerNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualServerDataNotice")  { e=kHuyaVirtualActorPacketType_VirtualServerDataNotice; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualInitDataToLiveClient")  { e=kHuyaVirtualActorPacketType_VirtualInitDataToLiveClient; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualCameraSwitch")  { e=kHuyaVirtualActorPacketType_VirtualCameraSwitch; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualDataReportEventWithKeyAndValue")  { e=kHuyaVirtualActorPacketType_VirtualDataReportEventWithKeyAndValue; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualTafDataReport")  { e=kHuyaVirtualActorPacketType_VirtualTafDataReport; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualMobileInteractiveGameStart")  { e=kHuyaVirtualActorPacketType_VirtualMobileInteractiveGameStart; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualActorWalk")  { e=kHuyaVirtualActorPacketType_VirtualActorWalk; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualGameBkgStream")  { e=kHuyaVirtualActorPacketType_VirtualGameBkgStream; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualActorDataChangeNotify")  { e=kHuyaVirtualActorPacketType_VirtualActorDataChangeNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_LiveStatusNotify")  { e=kHuyaVirtualActorPacketType_LiveStatusNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_GetInteractiveGameInfoList")  { e=kHuyaVirtualActorPacketType_GetInteractiveGameInfoList; return 0;}
        if(s == "kHuyaVirtualActorPacketType_GetInteractiveGameInfoListRes")  { e=kHuyaVirtualActorPacketType_GetInteractiveGameInfoListRes; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartInteractiveGame")  { e=kHuyaVirtualActorPacketType_StartInteractiveGame; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartInteractiveGameRes")  { e=kHuyaVirtualActorPacketType_StartInteractiveGameRes; return 0;}
        if(s == "kHuyaVirtualActorPacketType_EndInteractiveGame")  { e=kHuyaVirtualActorPacketType_EndInteractiveGame; return 0;}
        if(s == "kHuyaVirtualActorPacketType_EndInteractiveGameRes")  { e=kHuyaVirtualActorPacketType_EndInteractiveGameRes; return 0;}
        if(s == "kHuyaVirtualActorPacketType_PKStatusNotify")  { e=kHuyaVirtualActorPacketType_PKStatusNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_GiftItemInfoNotify")  { e=kHuyaVirtualActorPacketType_GiftItemInfoNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_ChatMessageInfoNotify")  { e=kHuyaVirtualActorPacketType_ChatMessageInfoNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_InteractiveGameDataNotify")  { e=kHuyaVirtualActorPacketType_InteractiveGameDataNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecovery")  { e=kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecovery; return 0;}
        if(s == "kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecoveryRes")  { e=kHuyaVirtualActorPacketType_CheckVirtualInteractiveGameDataRecoveryRes; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatReq")  { e=kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatReq; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatRsp")  { e=kHuyaVirtualActorPacketType_VirtualCrownGameHeatBeatRsp; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualOwnGameOrnamentNotify")  { e=kHuyaVirtualActorPacketType_VirtualOwnGameOrnamentNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameReq")  { e=kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameReq; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameRes")  { e=kHuyaVirtualActorPacketType_StartVirtualInteractiveTravelGameRes; return 0;}
        if(s == "kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameReq")  { e=kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameReq; return 0;}
        if(s == "kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameRes")  { e=kHuyaVirtualActorPacketType_PreStartVirtualInteractiveTravelGameRes; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelReq")  { e=kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelReq; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelRes")  { e=kHuyaVirtualActorPacketType_StartVirtualTravelGameLevelRes; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatReq")  { e=kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatReq; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatRsp")  { e=kHuyaVirtualActorPacketType_VirtualTravelGameHeartbeatRsp; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualTravelGuessWordsGameNotice")  { e=kHuyaVirtualActorPacketType_VirtualTravelGuessWordsGameNotice; return 0;}
        if(s == "kHuyaVirtualActorPacketType_VirtualTravelEmpowermentGameNotice")  { e=kHuyaVirtualActorPacketType_VirtualTravelEmpowermentGameNotice; return 0;}
        if(s == "kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameReq")  { e=kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameReq; return 0;}
        if(s == "kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameRes")  { e=kHuyaVirtualActorPacketType_EndVirtualInteractiveTravelGameRes; return 0;}
        if(s == "kHuyaVirtualActorPacketType_Virtual3DPKModeStatusNotify")  { e=kHuyaVirtualActorPacketType_Virtual3DPKModeStatusNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_Virtual3DPKStartStatusNotify")  { e=kHuyaVirtualActorPacketType_Virtual3DPKStartStatusNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_Virtual3DPKGuestActorControl")  { e=kHuyaVirtualActorPacketType_Virtual3DPKGuestActorControl; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartVirtual3DPK")  { e=kHuyaVirtualActorPacketType_StartVirtual3DPK; return 0;}
        if(s == "kHuyaVirtualActorPacketType_PrepareVirtual3DPK")  { e=kHuyaVirtualActorPacketType_PrepareVirtual3DPK; return 0;}
        if(s == "kHuyaVirtualActorPacketType_BattlePresenterInfo")  { e=kHuyaVirtualActorPacketType_BattlePresenterInfo; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartNewVirtual3DPK")  { e=kHuyaVirtualActorPacketType_StartNewVirtual3DPK; return 0;}
        if(s == "kHuyaVirtualActorPacketType_StartNewVirtual3DPKRsp")  { e=kHuyaVirtualActorPacketType_StartNewVirtual3DPKRsp; return 0;}
        if(s == "kHuyaVirtualActorPacketType_Virtual3DPKStatusNotice")  { e=kHuyaVirtualActorPacketType_Virtual3DPKStatusNotice; return 0;}
        if(s == "kHuyaVirtualActorPacketType_EndNewVirtual3DPK")  { e=kHuyaVirtualActorPacketType_EndNewVirtual3DPK; return 0;}
        if(s == "kHuyaVirtualActorPacketType_UpdateVirtual3DPKSignal")  { e=kHuyaVirtualActorPacketType_UpdateVirtual3DPKSignal; return 0;}
        if(s == "kHuyaVirtualActorPacketType_Enable3DPKNotify")  { e=kHuyaVirtualActorPacketType_Enable3DPKNotify; return 0;}
        if(s == "kHuyaVirtualActorPacketType_CheckVirtual3DPK")  { e=kHuyaVirtualActorPacketType_CheckVirtual3DPK; return 0;}
        if(s == "kHuyaVirtualActorPacketType_CheckVirtual3DPKRsp")  { e=kHuyaVirtualActorPacketType_CheckVirtual3DPKRsp; return 0;}
        if(s == "kHuyaVirtualActorPacketType_Live2DActorList")  { e=kHuyaVirtualActorPacketType_Live2DActorList; return 0;}
        if(s == "kHuyaVirtualActorPacketType_DXSharedHandleTransfer")  { e=kHuyaVirtualActorPacketType_DXSharedHandleTransfer; return 0;}

        return -1;
    }
}


#endif
